apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - image: nexus.safra.com.br/logstash:5.4.3-40a07
        imagePullPolicy: IfNotPresent
        name: logstash
        resources:
          limits:
            memory: "0"
          requests:
            memory: "0"
        securityContext:
          capabilities: {}
          privileged: true
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /run/log/journal
          name: runlogjournal
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /etc/docker-hostname
          name: dockerhostname
          readOnly: true
        - mountPath: /etc/localtime
          name: localtime
          readOnly: true
        - mountPath: /etc/sysconfig/docker
          name: dockercfg
          readOnly: true
      dnsPolicy: ClusterFirst
      nodeSelector:
        zone: ti
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /run/log/journal
        name: runlogjournal
      - hostPath:
          path: /var/log
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
        name: varlibdockercontainers
      - hostPath:
          path: /etc/hostname
        name: dockerhostname
      - hostPath:
          path: /etc/localtime
        name: localtime
      - hostPath:
          path: /etc/sysconfig/docker
        name: dockercfg
